name: Auto-merge dependabot updates

on: pull_request_target

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-22.04
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v6
      - run: gh pr review --approve --comment -b "LGTM!"
      - run: gh pr merge --squash
        env:
          GH_TOKEN: ${{ github.token }}
